const productsList = [
    {
        id: 1,
        title: "ELLERY X M'O CAPSULE",
        description: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        price: '$52.00',
        src: 'img/item-1.jpg',
    },
    {
        id: 2,
        title: "ELLERY X M'O CAPSULE",
        description: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        price: '$52.00',
        src: 'img/item-2.jpg',
    },
    {
        id: 3,
        title: "ELLERY X M'O CAPSULE",
        description: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        price: '$52.00',
        src: 'img/item-3.jpg',
    },
    {
        id: 4,
        title: "ELLERY X M'O CAPSULE",
        description: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        price: '$52.00',
        src: 'img/item-4.jpg',
    },
    {
        id: 5,
        title: "ELLERY X M'O CAPSULE",
        description: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        price: '$52.00',
        src: 'img/item-5.jpg',
    },    {
        id: 6,
        title: "ELLERY X M'O CAPSULE",
        description: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        price: '$52.00',
        src: 'img/item-6.jpg',
    },
    {
        id: 7,
        title: "ELLERY X M'O CAPSULE",
        description: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        price: '$52.00',
        src: 'img/item-7.jpg',
    },
    {
        id: 8,
        title: "ELLERY X M'O CAPSULE",
        description: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        price: '$52.00',
        src: 'img/item-8.jpg',
    },
    {
        id: 9,
        title: "ELLERY X M'O CAPSULE",
        description: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        price: '$52.00',
        src: 'img/item-9.jpg',
    },
    {
        id: 10,
        title: "ELLERY X M'O CAPSULE",
        description: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        price: '$52.00',
        src: 'img/item-10.jpg',
    },
    {
        id: 11,
        title: "ELLERY X M'O CAPSULE",
        description: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        price: '$52.00',
        src: 'img/item-11.jpg',
    },
    {
        id: 12,
        title: "ELLERY X M'O CAPSULE",
        description: 'Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.',
        price: '$52.00',
        src: 'img/item-12.jpg',
    },
];